/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class GetCalculateForAPIdaysInputBuilder {
    //the instance to build
    private GetCalculateForAPIdaysInput getCalculateForAPIdaysInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCalculateForAPIdaysInputBuilder() {
        getCalculateForAPIdaysInput = new GetCalculateForAPIdaysInput();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCalculateForAPIdaysInputBuilder operation(OperationTypeEnum operation) {
        getCalculateForAPIdaysInput.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCalculateForAPIdaysInputBuilder x(double x) {
        getCalculateForAPIdaysInput.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCalculateForAPIdaysInputBuilder y(double y) {
        getCalculateForAPIdaysInput.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCalculateForAPIdaysInput build() {
        return getCalculateForAPIdaysInput;
    }
}